project:
    name: fab-test
    module: github.com/user/fab-test
    created: 2026-01-07T14:42:57.365555831-08:00
features:
    validation:
        enabled: true
        mode: strict
    events:
        enabled: false
        bus_type: memory
    conditional:
        enabled: true
        etag_algorithm: sha256
    auth:
        enabled: false
    storage:
        enabled: true
        type: file
        db_driver: sqlite3
    reconciliation:
        enabled: false
        worker_count: 5
        requeue_delay: 5
generation:
    handlers: true
    storage: true
    client: true
    openapi: true
    events: false
    middleware: true
    reconciliation: false
