
// Generated by Fabrica v0.3.1-35-gaf1d3ba-dirty
// Template: init/go.mod.tmpl
// Generated: 2026-01-07T14:42:57-08:00

module github.com/user/fab-test

go 1.21

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/spf13/cobra v1.7.0
	github.com/spf13/viper v1.16.0
)
