// Generated by Fabrica v0.3.1-35-gaf1d3ba-dirty
// Template: init/go.mod.tmpl
// Generated: 2026-01-07T14:42:57-08:00

module github.com/user/fab-test

go 1.24.0

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/spf13/cobra v1.10.2
	github.com/spf13/viper v1.16.0
)

require (
	github.com/fsnotify/fsnotify v1.6.0 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/magiconair/properties v1.8.7 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/openchami/fabrica v0.3.2-0.20260107195938-af1d3bac2963
	github.com/pelletier/go-toml/v2 v2.0.8 // indirect
	github.com/spf13/afero v1.9.5 // indirect
	github.com/spf13/cast v1.5.1 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.10 // indirect
	github.com/subosito/gotenv v1.4.2 // indirect
	golang.org/x/sys v0.39.0 // indirect
	golang.org/x/text v0.32.0 // indirect
	gopkg.in/ini.v1 v1.67.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
