// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/rainest/fab-test/apis/pcs.example/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.PowerStatusComponent{}); err != nil {
		return fmt.Errorf("failed to register PowerStatusComponent: %w", err)
	}
	if err := gen.RegisterResource(&v1.Transition{}); err != nil {
		return fmt.Errorf("failed to register Transition: %w", err)
	}

	return nil
}
