// Code generated by Fabrica v0.3.1-35-gaf1d3ba-dirty. DO NOT EDIT.
// Template: apiversion/register.gotmpl
// Generated at: 2026-01-07T16:01:04-08:00

package apiversion

import (
	"github.com/openchami/fabrica/pkg/apiversion"
)

// Registry is the global API version registry
var Registry *apiversion.Registry

func init() {
	Registry = apiversion.NewRegistry()
	Registry.RegisterGroup(apiversion.Group{
		Name:           "pcs.example",
		StorageVersion: "v1",
		Spokes:         []string{"v1", "v2alpha1"},
	})
}

// GetRegistry returns the global version registry
func GetRegistry() *apiversion.Registry {
	return Registry
}
