// Code generated by Fabrica v0.3.1-35-gaf1d3ba-dirty. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-01-07T16:01:04-08:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for PowerStatusComponent resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /powerstatuscomponents (list all powerstatuscomponents)
//   - GET /powerstatuscomponents/{uid} (get specific PowerStatusComponent)
//   - POST /powerstatuscomponents (create new PowerStatusComponent)
//   - PUT /powerstatuscomponents/{uid} (update PowerStatusComponent spec)
//   - PATCH /powerstatuscomponents/{uid} (patch PowerStatusComponent spec)
//   - DELETE /powerstatuscomponents/{uid} (delete PowerStatusComponent)
//   - PUT /powerstatuscomponents/{uid}/status (update PowerStatusComponent status)
//   - PATCH /powerstatuscomponents/{uid}/status (patch PowerStatusComponent status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadPowerStatusComponent*/SavePowerStatusComponent*/DeletePowerStatusComponent*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/powerstatuscomponent/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadPowerStatusComponentWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/rainest/fab-test/apis/pcs.example/v1"

	"github.com/rainest/fab-test/internal/storage"
)

// GetPowerStatusComponents returns all PowerStatusComponent resources
func GetPowerStatusComponents(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	powerstatuscomponents, err := storage.LoadAllPowerStatusComponents(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load powerstatuscomponents: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, powerstatuscomponents)
}

// GetPowerStatusComponent returns a specific PowerStatusComponent resource by UID
func GetPowerStatusComponent(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("PowerStatusComponent UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadPowerStatusComponent() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	powerStatusComponent, err := storage.LoadPowerStatusComponent(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("PowerStatusComponent not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, powerStatusComponent)
}

// CreatePowerStatusComponent creates a new PowerStatusComponent resource
func CreatePowerStatusComponent(w http.ResponseWriter, r *http.Request) {
	var req CreatePowerStatusComponentRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("PowerStatusComponent")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	powerStatusComponent := &v1.PowerStatusComponent{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "PowerStatusComponent",
		Spec:       req.PowerStatusComponentSpec,
	}

	// Initialize metadata
	powerStatusComponent.Metadata.Name = req.Name
	powerStatusComponent.Metadata.UID = uid
	now := time.Now()
	powerStatusComponent.Metadata.CreatedAt = now
	powerStatusComponent.Metadata.UpdatedAt = now

	// Set labels and annotations
	if powerStatusComponent.Metadata.Labels == nil {
		powerStatusComponent.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		powerStatusComponent.Metadata.Labels[k] = v
	}
	if powerStatusComponent.Metadata.Annotations == nil {
		powerStatusComponent.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		powerStatusComponent.Metadata.Annotations[k] = v
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(powerStatusComponent); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), powerStatusComponent); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SavePowerStatusComponent(r.Context(), powerStatusComponent); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save PowerStatusComponent: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "PowerStatusComponent", powerStatusComponent.Metadata.UID, powerStatusComponent.Metadata.Name, powerStatusComponent); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for PowerStatusComponent %s: %v\n", powerStatusComponent.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, powerStatusComponent)
}

// UpdatePowerStatusComponent updates the spec of an existing PowerStatusComponent resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //powerstatuscomponents/{uid}/status to update status.
func UpdatePowerStatusComponent(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("PowerStatusComponent UID is required"))
		return
	}

	powerStatusComponent, err := storage.LoadPowerStatusComponent(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("PowerStatusComponent not found: %w", err))
		return
	}

	var req UpdatePowerStatusComponentRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Name != "" {
		powerStatusComponent.Metadata.Name = req.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	powerStatusComponent.Spec = req.PowerStatusComponentSpec

	// Update labels and annotations
	if powerStatusComponent.Metadata.Labels == nil {
		powerStatusComponent.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		powerStatusComponent.Metadata.Labels[k] = v
	}
	if powerStatusComponent.Metadata.Annotations == nil {
		powerStatusComponent.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		powerStatusComponent.Metadata.Annotations[k] = v
	}

	// Update timestamp
	powerStatusComponent.Metadata.UpdatedAt = time.Now()

	if err := storage.SavePowerStatusComponent(r.Context(), powerStatusComponent); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save PowerStatusComponent: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": powerStatusComponent.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "PowerStatusComponent", powerStatusComponent.Metadata.UID, powerStatusComponent.Metadata.Name, powerStatusComponent, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for PowerStatusComponent %s: %v\n", powerStatusComponent.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, powerStatusComponent)
}

// PatchPowerStatusComponent patches an existing PowerStatusComponent resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchPowerStatusComponent(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("PowerStatusComponent UID is required"))
		return
	}

	powerStatusComponent, err := storage.LoadPowerStatusComponent(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("PowerStatusComponent not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(powerStatusComponent.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &powerStatusComponent.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	powerStatusComponent.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SavePowerStatusComponent(r.Context(), powerStatusComponent); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched PowerStatusComponent: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": powerStatusComponent.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "PowerStatusComponent", powerStatusComponent.Metadata.UID, powerStatusComponent.Metadata.Name, powerStatusComponent, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for PowerStatusComponent %s: %v\n", powerStatusComponent.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, powerStatusComponent)
}

// UpdatePowerStatusComponentStatus updates only the status of a PowerStatusComponent resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdatePowerStatusComponentStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("PowerStatusComponent UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadPowerStatusComponent(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("PowerStatusComponent not found: %w", err))
		return
	}

	var statusUpdate v1.PowerStatusComponentStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SavePowerStatusComponent(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save PowerStatusComponent status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "PowerStatusComponent", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for PowerStatusComponent %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchPowerStatusComponentStatus patches only the status of a PowerStatusComponent resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchPowerStatusComponentStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("PowerStatusComponent UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadPowerStatusComponent(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("PowerStatusComponent not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SavePowerStatusComponent(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched PowerStatusComponent status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "PowerStatusComponent", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for PowerStatusComponent %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeletePowerStatusComponent deletes a PowerStatusComponent resource
func DeletePowerStatusComponent(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("PowerStatusComponent UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	powerStatusComponent, err := storage.LoadPowerStatusComponent(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("PowerStatusComponent not found: %w", err))
		return
	}

	if err := storage.DeletePowerStatusComponent(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete PowerStatusComponent: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "PowerStatusComponent", powerStatusComponent.Metadata.UID, powerStatusComponent.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for PowerStatusComponent %s: %v\n", powerStatusComponent.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "PowerStatusComponent deleted successfully",
		UID:     uid,
	})
}
