// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /powerstatuscomponents (PowerStatusComponent operations)
//   - /transitions (Transition operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("PowerStatusComponent", "powerstatuscomponent")

	resource.RegisterResourcePrefix("Transition", "transition")

	return nil
}

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {

	// PowerStatusComponent routes
	r.Route("/powerstatuscomponents", func(r chi.Router) {
		r.Get("/", GetPowerStatusComponents)
		r.Post("/", CreatePowerStatusComponent)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetPowerStatusComponent)
			r.Put("/", UpdatePowerStatusComponent)
			r.Patch("/", PatchPowerStatusComponent)
			r.Delete("/", DeletePowerStatusComponent)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdatePowerStatusComponentStatus)
				r.Patch("/", PatchPowerStatusComponentStatus)
			})
		})
	})

	// Transition routes
	r.Route("/transitions", func(r chi.Router) {
		r.Get("/", GetTransitions)
		r.Post("/", CreateTransition)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetTransition)
			r.Put("/", UpdateTransition)
			r.Patch("/", PatchTransition)
			r.Delete("/", DeleteTransition)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateTransitionStatus)
				r.Patch("/", PatchTransitionStatus)
			})
		})
	})

	// OpenAPI documentation routes
	r.Get("/openapi.json", ServeOpenAPISpec)
	r.Get("/docs", ServeSwaggerUI)
}
