// Code generated by Fabrica v0.3.1-35-gaf1d3ba-dirty. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-01-07T15:39:34-08:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Transition resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /transitions (list all transitions)
//   - GET /transitions/{uid} (get specific Transition)
//   - POST /transitions (create new Transition)
//   - PUT /transitions/{uid} (update Transition spec)
//   - PATCH /transitions/{uid} (patch Transition spec)
//   - DELETE /transitions/{uid} (delete Transition)
//   - PUT /transitions/{uid}/status (update Transition status)
//   - PATCH /transitions/{uid}/status (patch Transition status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadTransition*/SaveTransition*/DeleteTransition*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/transition/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadTransitionWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/user/fab-test/apis/pcs.example/v1"

	"github.com/user/fab-test/internal/storage"
)

// GetTransitions returns all Transition resources
func GetTransitions(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	transitions, err := storage.LoadAllTransitions(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load transitions: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, transitions)
}

// GetTransition returns a specific Transition resource by UID
func GetTransition(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Transition UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadTransition() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	transition, err := storage.LoadTransition(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Transition not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, transition)
}

// CreateTransition creates a new Transition resource
func CreateTransition(w http.ResponseWriter, r *http.Request) {
	var req CreateTransitionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Transition")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	transition := &v1.Transition{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "Transition",
		Spec:       req.TransitionSpec,
	}

	// Initialize metadata
	transition.Metadata.Name = req.Name
	transition.Metadata.UID = uid
	now := time.Now()
	transition.Metadata.CreatedAt = now
	transition.Metadata.UpdatedAt = now

	// Set labels and annotations
	if transition.Metadata.Labels == nil {
		transition.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		transition.Metadata.Labels[k] = v
	}
	if transition.Metadata.Annotations == nil {
		transition.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		transition.Metadata.Annotations[k] = v
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(transition); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), transition); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveTransition(r.Context(), transition); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Transition: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "Transition", transition.Metadata.UID, transition.Metadata.Name, transition); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for Transition %s: %v\n", transition.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, transition)
}

// UpdateTransition updates the spec of an existing Transition resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //transitions/{uid}/status to update status.
func UpdateTransition(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Transition UID is required"))
		return
	}

	transition, err := storage.LoadTransition(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Transition not found: %w", err))
		return
	}

	var req UpdateTransitionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Name != "" {
		transition.Metadata.Name = req.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	transition.Spec = req.TransitionSpec

	// Update labels and annotations
	if transition.Metadata.Labels == nil {
		transition.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		transition.Metadata.Labels[k] = v
	}
	if transition.Metadata.Annotations == nil {
		transition.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		transition.Metadata.Annotations[k] = v
	}

	// Update timestamp
	transition.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveTransition(r.Context(), transition); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Transition: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": transition.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "Transition", transition.Metadata.UID, transition.Metadata.Name, transition, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for Transition %s: %v\n", transition.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, transition)
}

// PatchTransition patches an existing Transition resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchTransition(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Transition UID is required"))
		return
	}

	transition, err := storage.LoadTransition(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Transition not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(transition.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &transition.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	transition.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveTransition(r.Context(), transition); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched Transition: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": transition.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "Transition", transition.Metadata.UID, transition.Metadata.Name, transition, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for Transition %s: %v\n", transition.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, transition)
}

// UpdateTransitionStatus updates only the status of a Transition resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateTransitionStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Transition UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadTransition(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Transition not found: %w", err))
		return
	}

	var statusUpdate v1.TransitionStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveTransition(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Transition status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "Transition", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for Transition %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchTransitionStatus patches only the status of a Transition resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchTransitionStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Transition UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadTransition(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Transition not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveTransition(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched Transition status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "Transition", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for Transition %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteTransition deletes a Transition resource
func DeleteTransition(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Transition UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	transition, err := storage.LoadTransition(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Transition not found: %w", err))
		return
	}

	if err := storage.DeleteTransition(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Transition: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "Transition", transition.Metadata.UID, transition.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for Transition %s: %v\n", transition.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Transition deleted successfully",
		UID:     uid,
	})
}
