// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'make dev' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil)
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"

	"github.com/user/fab-test/apis/pcs.example/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
	version    string // Optional API version for Accept/Content-Type headers
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:    c.baseURL,
		httpClient: c.httpClient,
		version:    version,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetPowerStatusComponents retrieves all powerstatuscomponents
func (c *Client) GetPowerStatusComponents(ctx context.Context) ([]v1.PowerStatusComponent, error) {
	var response []v1.PowerStatusComponent
	if err := c.doRequest(ctx, "GET", "/powerstatuscomponents", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetPowerStatusComponent retrieves a specific PowerStatusComponent by UID
func (c *Client) GetPowerStatusComponent(ctx context.Context, uid string) (*v1.PowerStatusComponent, error) {
	var result v1.PowerStatusComponent
	endpoint := fmt.Sprintf("/powerstatuscomponents/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreatePowerStatusComponent creates a new PowerStatusComponent
func (c *Client) CreatePowerStatusComponent(ctx context.Context, req CreatePowerStatusComponentRequest) (*v1.PowerStatusComponent, error) {
	var result v1.PowerStatusComponent
	if err := c.doRequest(ctx, "POST", "/powerstatuscomponents", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdatePowerStatusComponent updates an existing PowerStatusComponent
func (c *Client) UpdatePowerStatusComponent(ctx context.Context, uid string, req UpdatePowerStatusComponentRequest) (*v1.PowerStatusComponent, error) {
	var result v1.PowerStatusComponent
	endpoint := fmt.Sprintf("/powerstatuscomponents/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchPowerStatusComponent patches an existing PowerStatusComponent spec with the specified patch data and content type
func (c *Client) PatchPowerStatusComponent(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.PowerStatusComponent, error) {
	var result v1.PowerStatusComponent
	endpoint := fmt.Sprintf("/powerstatuscomponents/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdatePowerStatusComponentStatus updates only the status of an existing PowerStatusComponent
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdatePowerStatusComponentStatus(ctx context.Context, uid string, status v1.PowerStatusComponentStatus) (*v1.PowerStatusComponent, error) {
	var result v1.PowerStatusComponent
	endpoint := fmt.Sprintf("/powerstatuscomponents/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchPowerStatusComponentStatus patches only the status of an existing PowerStatusComponent
// Supports JSON Merge Patch by default. Use PatchPowerStatusComponentStatusWithType for other patch formats.
func (c *Client) PatchPowerStatusComponentStatus(ctx context.Context, uid string, patchData []byte) (*v1.PowerStatusComponent, error) {
	return c.PatchPowerStatusComponentStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchPowerStatusComponentStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchPowerStatusComponentStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.PowerStatusComponent, error) {
	var result v1.PowerStatusComponent
	endpoint := fmt.Sprintf("/powerstatuscomponents/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeletePowerStatusComponent deletes a PowerStatusComponent by UID
func (c *Client) DeletePowerStatusComponent(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/powerstatuscomponents/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetTransitions retrieves all transitions
func (c *Client) GetTransitions(ctx context.Context) ([]v1.Transition, error) {
	var response []v1.Transition
	if err := c.doRequest(ctx, "GET", "/transitions", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetTransition retrieves a specific Transition by UID
func (c *Client) GetTransition(ctx context.Context, uid string) (*v1.Transition, error) {
	var result v1.Transition
	endpoint := fmt.Sprintf("/transitions/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateTransition creates a new Transition
func (c *Client) CreateTransition(ctx context.Context, req CreateTransitionRequest) (*v1.Transition, error) {
	var result v1.Transition
	if err := c.doRequest(ctx, "POST", "/transitions", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateTransition updates an existing Transition
func (c *Client) UpdateTransition(ctx context.Context, uid string, req UpdateTransitionRequest) (*v1.Transition, error) {
	var result v1.Transition
	endpoint := fmt.Sprintf("/transitions/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchTransition patches an existing Transition spec with the specified patch data and content type
func (c *Client) PatchTransition(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Transition, error) {
	var result v1.Transition
	endpoint := fmt.Sprintf("/transitions/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateTransitionStatus updates only the status of an existing Transition
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateTransitionStatus(ctx context.Context, uid string, status v1.TransitionStatus) (*v1.Transition, error) {
	var result v1.Transition
	endpoint := fmt.Sprintf("/transitions/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchTransitionStatus patches only the status of an existing Transition
// Supports JSON Merge Patch by default. Use PatchTransitionStatusWithType for other patch formats.
func (c *Client) PatchTransitionStatus(ctx context.Context, uid string, patchData []byte) (*v1.Transition, error) {
	return c.PatchTransitionStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchTransitionStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchTransitionStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Transition, error) {
	var result v1.Transition
	endpoint := fmt.Sprintf("/transitions/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteTransition deletes a Transition by UID
func (c *Client) DeleteTransition(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/transitions/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
